module Api
  module V1
    class InboxesController < BaseController
      resource_description do
        short 'Inbox entries'
        description 'Create and retrieve inbox records. Name is auto-generated by the server.'
        formats ['json']
      end

      api :GET, '/v1/inboxes', 'List all inbox entries'
      def index
        inboxes = Inbox.order(created_at: :desc)
        render json: inboxes.map { |i| serialize(i) }
      end

      api :GET, '/v1/inboxes/:id', 'Fetch a single inbox entry'
      param :id, :number, required: true, desc: 'Inbox ID'
      def show
        inbox = Inbox.find(params[:id])
        render json: serialize(inbox)
      rescue ActiveRecord::RecordNotFound
        render json: { error: 'Not found' }, status: :not_found
      end

      api :POST, '/v1/inboxes', 'Create a new inbox entry'
      param :inbox, Hash, required: true do
        param :source,   String, desc: 'Origin identifier (e.g. "ratatui")'
        param :summary,  String, desc: 'Short human-readable summary'
        param :payload,  Hash,   desc: 'Arbitrary JSON payload'
        param :metadata, Hash,   desc: 'Arbitrary JSON metadata'
      end
      def create
        inbox = Inbox.new(inbox_params)
        if inbox.save
          render json: serialize(inbox), status: :created
        else
          render json: { errors: inbox.errors.as_json }, status: :unprocessable_entity
        end
      end

      private

      def inbox_params
        params.require(:inbox).permit(:source, :summary, payload: {}, metadata: {})
      end

      def serialize(inbox)
        {
          id: inbox.id,
          name: inbox.name,
          source: inbox.source,
          summary: inbox.summary,
          payload: inbox.payload,
          metadata: inbox.metadata,
          created_at: inbox.created_at,
          updated_at: inbox.updated_at
        }
      end
    end
  end
end
